// Generated by https://quicktype.io

export interface IDepartamentoResponse {
  id: number;
  name: string;
  description: string;
  cityCapitalId: number;
  municipalities: number;
  surface: number;
  population: number;
  phonePrefix: string;
  countryId: number;
  cityCapital: null;
  country: null;
  cities: null;
  regionId: number;
  region: null;
  naturalAreas: null;
  maps: null;
}
